### ISSUE TITLE
go dynamic function call

### ISSUE THREAD

**Issue by huahuayu** [vickydk/go-example#1]
hi, I have read you article [Go: Call a Function from String Name](https://medium.com/@vicky.kurniawan/go-call-a-function-from-string-name-30b41dcb9e12), very good article!

I have a similar case, would you please take a look? 

https://github.com/huahuayu/go-dynamic-call

**Comment by vickydk** [comment]
> hi, I have read you article [Go: Call a Function from String Name](https://medium.com/@vicky.kurniawan/go-call-a-function-from-string-name-30b41dcb9e12), very good article!
> 
> I have a similar case, would you please take a look?
> 
> https://github.com/huahuayu/go-dynamic-call

Hi,
First of all, you need to mapping your function using `map[string]interface{}` . without that we can't create dynamic function call.
we can't make it 100% dynamic, but we can make general rules to make it even more dynamic.

in your case I ever made it for dynamic GRPC req. call GRPC function from other package using the same approach.

I think I will create the library so everyone can use it.

**Comment by huahuayu** [comment]
hi @vickydk I have figured it out, a very concise reflect method, please [check](https://github.com/huahuayu/go-dynamic-call)

**Comment by vickydk** [comment]
@huahuayu 
yes you use that, if you want to know how many parameters in your dynamic function you can use this
```
method := reflect.ValueOf(obj).MethodByName(fn)
funcType := method.Type()
funcType.NumIn() //to get how many parametes the function have

**Comment by huahuayu** [comment]
yes, I see you use it in the example
